name: app_store
description: Curated marketplace for third-party applications on dahliaOS
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  expandable_page_view: ^1.0.14
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  provider: ^6.0.3
  recase: ^4.0.0
  shared_preferences: ^2.0.15
  xml: ^6.1.0
  yatl:
    git:
      url: https://github.com/HrX03/yatl
      path: yatl
  yatl_flutter:
    git:
      url: https://github.com/HrX03/yatl
      path: yatl_flutter
  yatl_gen:
    git:
      url: https://github.com/HrX03/yatl
      path: yatl_gen

dev_dependencies:
  build_runner: ^2.1.11
  lint: ^1.8.2

dependency_overrides:
  path: ^1.8.2

flutter:
  uses-material-design: true

#  assets:
#    - assets/