name: app_store
description: dahliaOS App store application
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  easy_localization: ^3.0.2-dev
  expandable_page_view: ^1.0.14
  flutter:
    sdk: flutter
  provider: ^6.0.3
  recase: ^4.0.0
  xml: ^5.3.0

dev_dependencies:
  lint: ^1.8.2
#  flutter_test:
#    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/locales/
