name: Locale generator
on:
  push:
    paths:
      - '**.xml'
    branches: [ main ]
jobs:
  locale_gen:
    name: Generate locales
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
        name: Checkout repository
      - uses: subosito/flutter-action@v2.4.0
        name: Prepare Flutter SDK
      - run: flutter channel dev
        name: Switch Flutter channel
      - run: flutter pub get
        name: Get dependencies
      - run: dart bin/locale_gen/locale_gen.dart
        name: Generate translations
      - run: git config user.name "dahliaOS-Bot" && git config user.email dahliaosofficial@gmail.com && git commit -am "Generated locales" && git push
        name: Push translations